source 'https://rubygems.org'

ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.6'

gem 'activerecord', '4.0.1'
gem 'activerecord-jdbcpostgresql-adapter', '1.3.3', platform: :jruby

group :test do
  gem 'rspec'
end

gemspec
